project:
  type: book



book:
  title: "Introduction to `pyspark`"
  author: "Pedro Duarte Faria"
  date: "2022-04-24"
  chapters:
    - index.qmd
    - Chapters/01-intro.qmd
    - Chapters/02-spark.qmd
    - Chapters/03-python.qmd
    - Chapters/04-dataframes.qmd
    - Chapters/references.qmd

bibliography: references.bib
number-sections: true
format:
  html:
    theme: cosmo



