project:
  type: book

engine: knitr


book:
  title: "Introduction to pyspark"
  author: "Pedro Duarte Faria"
  date: "2022-04-24"
  chapters:
    - index.qmd
    - 01-intro.qmd
    - 02-spark.qmd
    - 03-python.qmd
    - 04-dataframes.qmd
    - references.qmd

bibliography: references.bib
number-sections: true
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



